import type { Metadata } from 'next';
import '../globals.css';
import MouseMoveEffect from '@/components/mouse-move-effect';
import GradientBackground from '@/components/gradient-background';

export const metadata: Metadata = {
  title: 'roon',
  description: 'chat-appGenerated by create next app',
  icons: {
    icon: '/assets/logo-cat.png', 
  },
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <GradientBackground />
      <MouseMoveEffect />
      {children}
    </>
  );
}
