import { Inter } from 'next/font/google'; // Import the Inter font from Google
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '../globals.css';
import Provider from '@/components/Provider';
import SideBar from '@/components/SideBar';

// Load Inter font with Next.js font optimization
const inter = Inter({
  subsets: ['latin'],  // Specify the subset you need (e.g., latin)
  weights: ['400', '600'],  // Specify the font weights (e.g., regular and bold)
});

// Load custom local fonts (Geist Sans and Geist Mono)
const geistSans = localFont({
  src: '../fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: '../fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'chat-app',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${geistSans.variable} ${geistMono.variable} flex bg-gray-900 text-white overflow-hidden font-sans`}>
        <Provider>
          <SideBar />
          {children}
        </Provider>
      </body>
    </html>
  );
}

