import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import Provider from "@/components/Provider";
import TopBar from "@/components/TopBar";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "chat-app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" overflow-hidden bg-gray-900 text-white"
      >
        <Provider>
          <TopBar />
          {children}
        </Provider>
      </body>
    </html>
  );
}
